server.port: 8080
eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka
  instance.prefer-ip-address: true
spring:
  application.name: gateway-microservice
  cloud:
    gateway:
      routes:
        - id: reservation-microservice
          uri: lb://reservation-microservice
          predicates:
            - Path=/api/v1/reservations/**
        - id: room-microservice
          uri: lb://room-microservice
          predicates:
            - Path=/api/v1/rooms/**