server.port: 8081
eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka
  instance.prefer-ip-address: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate