server.port: 8083
eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka
  instance.prefer-ip-address: true
database:
  name: hotel_db
  host: localhost
  port: 5432
spring:
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate