server.port: 8081
eureka:
  client.serviceUrl.defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance.prefer-ip-address: true
database:
  name: ${DB_NAME:hotel_db}
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:password}

kafka:
  host: ${KAFKA_HOST:localhost}
  port: ${KAFKA_PORT:9092}
  bootstrapAddress: ${kafka.host}:${kafka.port}

spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrapAddress}
  datasource:
    username: ${database.username}
    password: ${database.password}
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate